# Generated by Django 4.2.4 on 2023-10-25 06:02

from django.db import migrations


def add_unique_brands(apps, schema_editor):
    shoe_model = apps.get_model('main_app', 'Shoe')
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')

    unique_brands = shoe_model.objects.values_list('brand', flat=True).distinct()

    unique_brands_to_add = [unique_brands_model(brand_name=brand) for brand in unique_brands]

    unique_brands_model.objects.bulk_create(unique_brands_to_add)


def delete_unique_brands(apps, schema_editor):
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')
    unique_brands_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(add_unique_brands, reverse_code=delete_unique_brands)
    ]
