# Generated by Django 4.2.4 on 2023-10-25 11:58

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    persons = person_model.objects.all()

    for current_person in persons:
        if current_person.age <= 12:
            current_person.age_group = 'Child'
        elif current_person.age <= 17:
            current_person.age_group = 'Teen'
        else:
            current_person.age_group = 'Adult'

    person_model.objects.bulk_update(persons, ['age_group'])


def set_default_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    persons = person_model.objects.all()

    default_age_group = person_model._meta.get_field('age_group').default

    for person in persons:
        person.age_group = default_age_group

    person_model.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_default_age_group)
    ]
