# Generated by Django 4.2.4 on 2023-10-25 13:47

from django.db import migrations


def set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.price = len(phone.brand) * 120

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        if phone.price < 750:
            phone.category = 'Cheap'
        else:
            phone.category = 'Expensive'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def set_category_and_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def revert_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    default_category = smartphone_model._meta.get_field('category').default

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.price = 0
        phone.category = default_category

    smartphone_model.objects.bulk_update(smartphones, ['price', 'category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(code=set_category_and_price, reverse_code=revert_price_and_category)
    ]
