# Generated by Django 4.2.4 on 2023-10-26 08:18

from django.db import migrations
from django.utils import timezone


def set_delivery_and_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    for order in order_model.objects.all():
        if order.status == 'PE':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'CO':
            order.warranty = '24 months'
            order.save()
        elif order.status == 'CA':
            order.delete()


def set_default_delivery_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    orders = order_model.objects.all()

    default_warranty = order_model._meta.get_field('warranty').default

    for order in orders:
        if order.status == 'PE':
            order.delivery = None
        elif order.status == 'CO':
            order.warranty = default_warranty

    order_model.objects.bulk_update(orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(code=set_delivery_and_warranty, reverse_code=set_default_delivery_warranty)
    ]
